from yacs.config import CfgNode as CN

_C = CN()
_C.LUNA = CN()
_C.LUNA.PATH = ""

_C.LUNA.DIR = CN()
_C.LUNA.DIR.RAW = ""
_C.LUNA.DIR.SEGMENT = "'"

_C.LUNA.FILE = CN()
_C.LUNA.FILE.ANNOTS = ""
_C.LUNA.FILE.CANDID = ""

_C.LUNA_OUT = CN()
_C.LUNA_OUT.PATH = ""

_C.LUNA_OUT.DIR = CN()
_C.LUNA_OUT.DIR.PREP_IMG = ""
_C.LUNA_OUT.DIR.PREP_SEG = ""
_C.LUNA_OUT.DIR.PROCSED = ""

_C.LUNA_OUT.FILE = CN()
_C.LUNA_OUT.FILE.SHORTER = ""
_C.LUNA_OUT.FILE.ABBR_ANNO = ""

_C.TEST = CN()
_C.TEST.DIR_SAVE = ""
_C.TEST.DIR_DATA = ""
_C.TEST.DIR_CKPT = ""
_C.TEST.DIR_CSV  = ""
_C.TEST.FILE_CKPT = ""
_C.TEST.NAMELIST = ""
_C.TEST.GPU = ""
_C.TEST.MODEL = ""

_C.TRAIN = CN()
_C.TRAIN.DIR_SAVE = ""
_C.TRAIN.DIR_DATA = ""
_C.TRAIN.DIR_CKPT = ""
_C.TRAIN.GPU = ""
_C.TRAIN.MODEL = ""
_C.TRAIN.RESUME = ""
_C.TRAIN.START_EPOCH = 0
_C.TRAIN.FRAC_FOR_TRAIN = 0.0
_C.TRAIN.BATCH_SIZE  = 1
_C.TRAIN.NUM_WORKERS = 0
_C.TRAIN.LEARNING_RATE = 0.00
_C.TRAIN.MOMENTUM = 0.0
_C.TRAIN.WEIGHT_DECAY = 0.0000
_C.TRAIN.NUM_EPOCHS  = 0
_C.TRAIN.NAME_LIST = ""
_C.TRAIN.LOG_TRAIN = ""
_C.TRAIN.LOG_VALID = ""

def get_cfg_defaults():
    return _C.clone()

